export const studentsConstants = {
    GET_ALL_STUDENTS_REQUEST: "GET_ALL_STUDENTS_REQUEST",
    GET_ALL_STUDENTS_SUCCESS: "GET_ALL_STUDENTS_SUCCESS",
    GET_ALL_STUDENTS_FAILURE: "GET_ALL_STUDENTS_FAILURE",
  
    DELETE_STUDENT_BY_ID_REQUEST: "DELETE_STUDENT_BY_ID_REQUEST",
    DELETE_STUDENT_BY_ID_SUCCESS: "DELETE_STUDENT_BY_ID_SUCCESS",
    DELETE_STUDENT_BY_ID_FAILURE: "DELETE_STUDENT_BY_ID_FAILURE",
  
    ADD_STUDENT_REQUEST: "ADD_STUDENT_REQUEST",
    ADD_STUDENT_SUCCESS: "ADD_STUDENT_REQUEST",
    ADD_STUDENT_FAILURE: "ADD_STUDENT_FAILURE",
  };